### ISSUE TITLE
Simpleparse support on Python 3.9?

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [mcfletch/simpleparse#16]
Dear all,

Is simpleparse supported on Python 3.9?

Thank you

**Comment by hernot** [comment]
Can't tell about current release, whether there is a 3.9 wheel or whether pip would try to build from sources. But build tests pass under 3.9 so i'd expect that in worst if now wheel is available for 3.9 pip build should succeed, as apart from Python sources simple parse sources contain everything needed, as far as i can see.

**Comment by aliaksei-chareshneu** [comment]
Thank you
